// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBoj5JYalguq_puzwIIX4u0w-i0W_yO-o',
    appId: '1:249244186743:web:1e78098e061bdda4fdae72',
    messagingSenderId: '249244186743',
    projectId: 'prepaalumnos-14629',
    authDomain: 'prepaalumnos-14629.firebaseapp.com',
    storageBucket: 'prepaalumnos-14629.appspot.com',
    measurementId: 'G-4KDLXCL3NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVQsSSX2xJwIdpkJjTgXqPYcqftbCaC8',
    appId: '1:249244186743:android:4308fbacccb6a0fffdae72',
    messagingSenderId: '249244186743',
    projectId: 'prepaalumnos-14629',
    storageBucket: 'prepaalumnos-14629.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBYOQVL5YCTDxihioCCGFHT_45WlBZ5o',
    appId: '1:249244186743:ios:78efaab77598cf8efdae72',
    messagingSenderId: '249244186743',
    projectId: 'prepaalumnos-14629',
    storageBucket: 'prepaalumnos-14629.appspot.com',
    iosClientId: '249244186743-s7ubr05mh45hvul4cr3ncsjqchg3n3ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoPrepa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBYOQVL5YCTDxihioCCGFHT_45WlBZ5o',
    appId: '1:249244186743:ios:78efaab77598cf8efdae72',
    messagingSenderId: '249244186743',
    projectId: 'prepaalumnos-14629',
    storageBucket: 'prepaalumnos-14629.appspot.com',
    iosClientId: '249244186743-s7ubr05mh45hvul4cr3ncsjqchg3n3ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoPrepa',
  );
}
